-- ============================================================================
-- Cortex Code Demo Schema — Healthcare RCM
-- Creates RCM-shaped tables for Emergency Medicine billing demo
-- ============================================================================

USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS CORTEX_CODE_RCM_DEMO;
CREATE SCHEMA IF NOT EXISTS CORTEX_CODE_RCM_DEMO.RAW;
CREATE SCHEMA IF NOT EXISTS CORTEX_CODE_RCM_DEMO.STAGING;
CREATE SCHEMA IF NOT EXISTS CORTEX_CODE_RCM_DEMO.MARTS;

USE SCHEMA CORTEX_CODE_RCM_DEMO.RAW;

CREATE OR REPLACE TABLE FACILITIES (
    FACILITY_ID         INT,
    FACILITY_NAME       VARCHAR(200),
    FACILITY_TYPE       VARCHAR(50),
    STATE               VARCHAR(2),
    CITY                VARCHAR(100),
    BED_COUNT           INT,
    CONTRACT_START_DATE DATE,
    IS_ACTIVE           BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE PROVIDERS (
    PROVIDER_NPI        VARCHAR(10),
    PROVIDER_NAME       VARCHAR(200),
    PROVIDER_SPECIALTY  VARCHAR(100),
    CREDENTIAL          VARCHAR(20),
    FACILITY_ID         INT,
    HIRE_DATE           DATE,
    IS_ACTIVE           BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE PAYERS (
    PAYER_ID            INT,
    PAYER_NAME          VARCHAR(200),
    PAYER_TYPE          VARCHAR(50),
    STATE               VARCHAR(2),
    CONTRACT_RATE_PCT   DECIMAL(5,2),
    IS_IN_NETWORK       BOOLEAN
);

CREATE OR REPLACE TABLE ENCOUNTERS (
    ENCOUNTER_ID        VARCHAR(20),
    PATIENT_ACCOUNT_NUM VARCHAR(20),
    FACILITY_ID         INT,
    PROVIDER_NPI        VARCHAR(10),
    PAYER_ID            INT,
    ENCOUNTER_DATE      TIMESTAMP,
    DISCHARGE_DATE      TIMESTAMP,
    CHIEF_COMPLAINT     VARCHAR(500),
    ACUITY_LEVEL        INT,
    DISPOSITION         VARCHAR(100),
    LENGTH_OF_STAY_MIN  INT
);

CREATE OR REPLACE TABLE CLAIMS (
    CLAIM_ID                VARCHAR(20),
    ENCOUNTER_ID            VARCHAR(20),
    PATIENT_ACCOUNT_NUM     VARCHAR(20),
    FACILITY_ID             INT,
    PROVIDER_NPI            VARCHAR(10),
    PAYER_ID                INT,
    SERVICE_DATE            DATE,
    CPT_CODE                VARCHAR(10),
    CPT_DESCRIPTION         VARCHAR(500),
    PRIMARY_DIAGNOSIS_CODE  VARCHAR(10),
    DIAGNOSIS_DESCRIPTION   VARCHAR(500),
    SERVICE_LINE_CODE       VARCHAR(10),
    BILLED_AMOUNT           DECIMAL(12,2),
    ALLOWED_AMOUNT          DECIMAL(12,2),
    PAID_AMOUNT             DECIMAL(12,2),
    PATIENT_RESPONSIBILITY  DECIMAL(12,2),
    ADJUSTMENT_AMOUNT       DECIMAL(12,2),
    CLAIM_STATUS            VARCHAR(20),
    DENIAL_REASON_CODE      VARCHAR(20),
    DENIAL_REASON_DESC      VARCHAR(500),
    FIRST_SUBMISSION_DATE   DATE,
    FIRST_PAYMENT_DATE      DATE,
    LAST_UPDATED            TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DENIAL_CODES (
    DENIAL_REASON_CODE  VARCHAR(20),
    DENIAL_CATEGORY     VARCHAR(100),
    DENIAL_DESCRIPTION  VARCHAR(500),
    IS_APPEALABLE       BOOLEAN,
    TYPICAL_RESOLUTION  VARCHAR(200)
);

USE SCHEMA CORTEX_CODE_RCM_DEMO.STAGING;

CREATE OR REPLACE TABLE STG_CLAIMS_DAILY (
    CLAIM_ID                VARCHAR(20),
    ENCOUNTER_ID            VARCHAR(20),
    PATIENT_ACCOUNT_NUM     VARCHAR(20),
    FACILITY_ID             INT,
    PROVIDER_NPI            VARCHAR(10),
    PAYER_ID                INT,
    SERVICE_DATE            DATE,
    CPT_CODE                VARCHAR(10),
    PRIMARY_DIAGNOSIS_CODE  VARCHAR(10),
    SERVICE_LINE_CODE       VARCHAR(10),
    BILLED_AMOUNT           DECIMAL(12,2),
    ALLOWED_AMOUNT          DECIMAL(12,2),
    PAID_AMOUNT             DECIMAL(12,2),
    PATIENT_RESPONSIBILITY  DECIMAL(12,2),
    ADJUSTMENT_AMOUNT       DECIMAL(12,2),
    CLAIM_STATUS            VARCHAR(20),
    DENIAL_REASON_CODE      VARCHAR(20),
    FIRST_PAYMENT_DATE      DATE,
    LOADED_AT               TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE STREAM STG_CLAIMS_STREAM ON TABLE STG_CLAIMS_DAILY
    APPEND_ONLY = TRUE;
