-- ============================================================================
-- Cortex Code Demo — Staging → Mart Transformation + Incremental Pipeline
-- Demo Part 3: Pipeline Development (DML transformation + Task/Stream)
-- "Answer key" — this is what Cortex Code should produce when prompted
-- ============================================================================

USE SCHEMA CORTEX_CODE_RCM_DEMO.MARTS;

-- ---------------------------------------------------------------------------
-- STEP 1: Collections Per Visit Mart (the core transformation)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TABLE MART_EM_COLLECTIONS_PER_VISIT AS
WITH deduplicated_claims AS (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY CLAIM_ID
            ORDER BY LAST_UPDATED DESC
        ) AS rn
    FROM CORTEX_CODE_RCM_DEMO.RAW.CLAIMS
    WHERE SERVICE_LINE_CODE = 'EM'
      AND CLAIM_STATUS IN ('PAID', 'DENIED', 'PARTIAL', 'ADJUDICATED')
),
ranked_claims AS (
    SELECT
        c.CLAIM_ID,
        c.ENCOUNTER_ID,
        c.PATIENT_ACCOUNT_NUM,
        c.FACILITY_ID,
        f.FACILITY_NAME,
        c.PROVIDER_NPI,
        p.PROVIDER_NAME,
        p.PROVIDER_SPECIALTY,
        c.SERVICE_DATE,
        c.CPT_CODE,
        c.CPT_DESCRIPTION,
        c.PRIMARY_DIAGNOSIS_CODE,
        c.PAYER_ID,
        py.PAYER_NAME,
        py.PAYER_TYPE,
        c.BILLED_AMOUNT,
        COALESCE(c.ALLOWED_AMOUNT, 0) AS ALLOWED_AMOUNT,
        COALESCE(c.PAID_AMOUNT, 0) AS PAID_AMOUNT,
        COALESCE(c.PATIENT_RESPONSIBILITY, 0) AS PATIENT_RESPONSIBILITY,
        COALESCE(c.ADJUSTMENT_AMOUNT, 0) AS ADJUSTMENT_AMOUNT,
        c.CLAIM_STATUS,
        c.DENIAL_REASON_CODE,
        c.DENIAL_REASON_DESC,
        DATEDIFF('DAY', c.SERVICE_DATE, c.FIRST_PAYMENT_DATE) AS DAYS_TO_PAYMENT,
        IFF(c.CLAIM_STATUS = 'DENIED', 1, 0) AS IS_DENIED,
        CASE
            WHEN c.CPT_CODE BETWEEN '99281' AND '99285'
            THEN RIGHT(c.CPT_CODE, 1)::INT
        END AS EM_LEVEL,
        ROW_NUMBER() OVER (
            PARTITION BY c.ENCOUNTER_ID
            ORDER BY c.BILLED_AMOUNT DESC
        ) AS CLAIM_RANK
    FROM deduplicated_claims c
    JOIN CORTEX_CODE_RCM_DEMO.RAW.FACILITIES f ON c.FACILITY_ID = f.FACILITY_ID
    JOIN CORTEX_CODE_RCM_DEMO.RAW.PROVIDERS p ON c.PROVIDER_NPI = p.PROVIDER_NPI
    JOIN CORTEX_CODE_RCM_DEMO.RAW.PAYERS py ON c.PAYER_ID = py.PAYER_ID
    WHERE c.rn = 1
)
SELECT
    FACILITY_ID,
    FACILITY_NAME,
    PROVIDER_NPI,
    PROVIDER_NAME,
    DATE_TRUNC('MONTH', SERVICE_DATE) AS REPORT_MONTH,
    COUNT(DISTINCT ENCOUNTER_ID) AS TOTAL_VISITS,
    COUNT(DISTINCT CLAIM_ID) AS TOTAL_CLAIMS,
    SUM(BILLED_AMOUNT) AS TOTAL_BILLED,
    SUM(PAID_AMOUNT) AS TOTAL_COLLECTED,
    SUM(ADJUSTMENT_AMOUNT) AS TOTAL_ADJUSTMENTS,
    SUM(PATIENT_RESPONSIBILITY) AS TOTAL_PATIENT_RESP,
    ROUND(
        IFF(COUNT(DISTINCT ENCOUNTER_ID) > 0,
            SUM(PAID_AMOUNT) / COUNT(DISTINCT ENCOUNTER_ID),
            0),
        2
    ) AS COLLECTIONS_PER_VISIT,
    ROUND(
        IFF(SUM(BILLED_AMOUNT) > 0,
            SUM(PAID_AMOUNT) / SUM(BILLED_AMOUNT) * 100,
            0),
        2
    ) AS COLLECTION_RATE,
    SUM(IS_DENIED) AS DENIAL_COUNT,
    ROUND(
        IFF(COUNT(*) > 0,
            SUM(IS_DENIED) / COUNT(*) * 100,
            0),
        2
    ) AS DENIAL_RATE,
    ROUND(AVG(DAYS_TO_PAYMENT), 1) AS AVG_DAYS_TO_PAYMENT,
    ROUND(AVG(EM_LEVEL), 2) AS AVG_EM_LEVEL,
    LISTAGG(DISTINCT IFF(IS_DENIED = 1, DENIAL_REASON_CODE, NULL), ', ')
        WITHIN GROUP (ORDER BY DENIAL_REASON_CODE) AS DENIAL_REASONS,
    CURRENT_TIMESTAMP() AS GENERATED_AT
FROM ranked_claims
WHERE CLAIM_RANK = 1
GROUP BY
    FACILITY_ID,
    FACILITY_NAME,
    PROVIDER_NPI,
    PROVIDER_NAME,
    DATE_TRUNC('MONTH', SERVICE_DATE)
ORDER BY
    FACILITY_NAME,
    PROVIDER_NAME,
    REPORT_MONTH;


-- ---------------------------------------------------------------------------
-- STEP 2: Incremental pipeline using Stream + Task
-- ---------------------------------------------------------------------------

CREATE OR REPLACE STREAM CORTEX_CODE_RCM_DEMO.STAGING.STG_CLAIMS_STREAM
    ON TABLE CORTEX_CODE_RCM_DEMO.STAGING.STG_CLAIMS_DAILY
    APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK CORTEX_CODE_RCM_DEMO.STAGING.TASK_LOAD_EM_CLAIMS
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '60 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('CORTEX_CODE_RCM_DEMO.STAGING.STG_CLAIMS_STREAM')
AS
MERGE INTO CORTEX_CODE_RCM_DEMO.RAW.CLAIMS tgt
USING (
    SELECT
        s.CLAIM_ID,
        s.ENCOUNTER_ID,
        s.PATIENT_ACCOUNT_NUM,
        s.FACILITY_ID,
        s.PROVIDER_NPI,
        s.PAYER_ID,
        s.SERVICE_DATE,
        s.CPT_CODE,
        NULL AS CPT_DESCRIPTION,
        s.PRIMARY_DIAGNOSIS_CODE,
        NULL AS DIAGNOSIS_DESCRIPTION,
        s.SERVICE_LINE_CODE,
        s.BILLED_AMOUNT,
        s.ALLOWED_AMOUNT,
        s.PAID_AMOUNT,
        s.PATIENT_RESPONSIBILITY,
        s.ADJUSTMENT_AMOUNT,
        s.CLAIM_STATUS,
        s.DENIAL_REASON_CODE,
        CASE WHEN s.DENIAL_REASON_CODE IS NOT NULL
             THEN 'Claim denied - see denial reason code'
        END AS DENIAL_REASON_DESC,
        s.SERVICE_DATE AS FIRST_SUBMISSION_DATE,
        s.FIRST_PAYMENT_DATE,
        CURRENT_TIMESTAMP() AS LAST_UPDATED
    FROM CORTEX_CODE_RCM_DEMO.STAGING.STG_CLAIMS_STREAM s
) src
ON tgt.CLAIM_ID = src.CLAIM_ID
WHEN MATCHED THEN UPDATE SET
    tgt.PAID_AMOUNT = src.PAID_AMOUNT,
    tgt.CLAIM_STATUS = src.CLAIM_STATUS,
    tgt.DENIAL_REASON_CODE = src.DENIAL_REASON_CODE,
    tgt.LAST_UPDATED = src.LAST_UPDATED
WHEN NOT MATCHED THEN INSERT (
    CLAIM_ID, ENCOUNTER_ID, PATIENT_ACCOUNT_NUM, FACILITY_ID, PROVIDER_NPI,
    PAYER_ID, SERVICE_DATE, CPT_CODE, CPT_DESCRIPTION, PRIMARY_DIAGNOSIS_CODE,
    DIAGNOSIS_DESCRIPTION, SERVICE_LINE_CODE, BILLED_AMOUNT, ALLOWED_AMOUNT,
    PAID_AMOUNT, PATIENT_RESPONSIBILITY, ADJUSTMENT_AMOUNT, CLAIM_STATUS,
    DENIAL_REASON_CODE, DENIAL_REASON_DESC, FIRST_SUBMISSION_DATE, FIRST_PAYMENT_DATE,
    LAST_UPDATED
) VALUES (
    src.CLAIM_ID, src.ENCOUNTER_ID, src.PATIENT_ACCOUNT_NUM, src.FACILITY_ID, src.PROVIDER_NPI,
    src.PAYER_ID, src.SERVICE_DATE, src.CPT_CODE, src.CPT_DESCRIPTION, src.PRIMARY_DIAGNOSIS_CODE,
    src.DIAGNOSIS_DESCRIPTION, src.SERVICE_LINE_CODE, src.BILLED_AMOUNT, src.ALLOWED_AMOUNT,
    src.PAID_AMOUNT, src.PATIENT_RESPONSIBILITY, src.ADJUSTMENT_AMOUNT, src.CLAIM_STATUS,
    src.DENIAL_REASON_CODE, src.DENIAL_REASON_DESC, src.FIRST_SUBMISSION_DATE, src.FIRST_PAYMENT_DATE,
    src.LAST_UPDATED
);

-- Refresh the mart after incremental load
CREATE OR REPLACE TASK CORTEX_CODE_RCM_DEMO.MARTS.TASK_REFRESH_EM_COLLECTIONS
    WAREHOUSE = COMPUTE_WH
    AFTER CORTEX_CODE_RCM_DEMO.STAGING.TASK_LOAD_EM_CLAIMS
AS
CREATE OR REPLACE TABLE CORTEX_CODE_RCM_DEMO.MARTS.MART_EM_COLLECTIONS_PER_VISIT AS
WITH deduplicated_claims AS (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY CLAIM_ID ORDER BY LAST_UPDATED DESC) AS rn
    FROM CORTEX_CODE_RCM_DEMO.RAW.CLAIMS
    WHERE SERVICE_LINE_CODE = 'EM'
      AND CLAIM_STATUS IN ('PAID', 'DENIED', 'PARTIAL', 'ADJUDICATED')
),
ranked_claims AS (
    SELECT
        c.CLAIM_ID, c.ENCOUNTER_ID, c.FACILITY_ID, f.FACILITY_NAME,
        c.PROVIDER_NPI, p.PROVIDER_NAME, c.SERVICE_DATE,
        c.BILLED_AMOUNT, COALESCE(c.PAID_AMOUNT, 0) AS PAID_AMOUNT,
        COALESCE(c.ADJUSTMENT_AMOUNT, 0) AS ADJUSTMENT_AMOUNT,
        COALESCE(c.PATIENT_RESPONSIBILITY, 0) AS PATIENT_RESPONSIBILITY,
        c.CLAIM_STATUS, c.DENIAL_REASON_CODE,
        DATEDIFF('DAY', c.SERVICE_DATE, c.FIRST_PAYMENT_DATE) AS DAYS_TO_PAYMENT,
        IFF(c.CLAIM_STATUS = 'DENIED', 1, 0) AS IS_DENIED,
        CASE WHEN c.CPT_CODE BETWEEN '99281' AND '99285' THEN RIGHT(c.CPT_CODE, 1)::INT END AS EM_LEVEL,
        ROW_NUMBER() OVER (PARTITION BY c.ENCOUNTER_ID ORDER BY c.BILLED_AMOUNT DESC) AS CLAIM_RANK
    FROM deduplicated_claims c
    JOIN CORTEX_CODE_RCM_DEMO.RAW.FACILITIES f ON c.FACILITY_ID = f.FACILITY_ID
    JOIN CORTEX_CODE_RCM_DEMO.RAW.PROVIDERS p ON c.PROVIDER_NPI = p.PROVIDER_NPI
    WHERE c.rn = 1
)
SELECT
    FACILITY_ID, FACILITY_NAME, PROVIDER_NPI, PROVIDER_NAME,
    DATE_TRUNC('MONTH', SERVICE_DATE) AS REPORT_MONTH,
    COUNT(DISTINCT ENCOUNTER_ID) AS TOTAL_VISITS,
    COUNT(DISTINCT CLAIM_ID) AS TOTAL_CLAIMS,
    SUM(BILLED_AMOUNT) AS TOTAL_BILLED,
    SUM(PAID_AMOUNT) AS TOTAL_COLLECTED,
    SUM(ADJUSTMENT_AMOUNT) AS TOTAL_ADJUSTMENTS,
    SUM(PATIENT_RESPONSIBILITY) AS TOTAL_PATIENT_RESP,
    ROUND(IFF(COUNT(DISTINCT ENCOUNTER_ID) > 0, SUM(PAID_AMOUNT) / COUNT(DISTINCT ENCOUNTER_ID), 0), 2) AS COLLECTIONS_PER_VISIT,
    ROUND(IFF(SUM(BILLED_AMOUNT) > 0, SUM(PAID_AMOUNT) / SUM(BILLED_AMOUNT) * 100, 0), 2) AS COLLECTION_RATE,
    SUM(IS_DENIED) AS DENIAL_COUNT,
    ROUND(IFF(COUNT(*) > 0, SUM(IS_DENIED) / COUNT(*) * 100, 0), 2) AS DENIAL_RATE,
    ROUND(AVG(DAYS_TO_PAYMENT), 1) AS AVG_DAYS_TO_PAYMENT,
    ROUND(AVG(EM_LEVEL), 2) AS AVG_EM_LEVEL,
    CURRENT_TIMESTAMP() AS GENERATED_AT
FROM ranked_claims
WHERE CLAIM_RANK = 1
GROUP BY FACILITY_ID, FACILITY_NAME, PROVIDER_NPI, PROVIDER_NAME, DATE_TRUNC('MONTH', SERVICE_DATE)
ORDER BY FACILITY_NAME, PROVIDER_NAME, REPORT_MONTH;

-- To activate: ALTER TASK ... RESUME (run child first, then parent)
-- ALTER TASK CORTEX_CODE_RCM_DEMO.MARTS.TASK_REFRESH_EM_COLLECTIONS RESUME;
-- ALTER TASK CORTEX_CODE_RCM_DEMO.STAGING.TASK_LOAD_EM_CLAIMS RESUME;
